### ISSUE TITLE
Service `db` requires `platform: linux/x86_64` under MacOS

### ISSUE THREAD

**Issue by jissereitsma** [mediact/docker-compose-development-manager#35]
While playing with this Docker setup, @WOH2021 found out that he couldn't get the `db` service, unless the line `platform: linux/x86_64` was added to his `docker-compose.yml` file. He's running MacOS. The end-result would look like so:

```yaml
  db:
    platform: linux/x86_64
    image: percona:8
    ...
```

Would this be something to be added to the `docker-compose.yml` file directly? Or perhaps in the docs here?

For reference: https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8
